management:
  endpoint:
    health:
      showd-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: test
    export:
      prometheus:
        enabled: true
